### ISSUE TITLE
Homework-1

### ISSUE THREAD

**Issue by maheshbhuvanagiri** [amshekar/epam-js-angular-training#1]
1. Use proper indents and spaces in the code

Get Middle Character
a) len/2 - this expression can be assigned to a variable and use that instead of calculating at each location.
b) if(len==1) is not needed, when s='A', second if statement will be true and it will not be checking the last if condition.
c) use { } brackets even if  we have one line of statement. (ex: in last if block { } brackets are missing

Transport on vacation
a) Number(d)-- No need to call Number function in this example, as we will be passing number in this example.
b) (days*baseFare) -- avoid repetitive calculations.

**Comment by amshekar** [comment]
@maheshbhuvanagiri  Implemented the review comments.

**a) Number(d)-- No need to call Number function is this example, as we will be passing number in this example.**

> Here i added few test cases by passing strings so added conversion function . Now removed both test cases and the conversion

Please review and provide valuable suggestions and the material /best practises to follow w.r.t Home-work-1 .
Appreciate your suggestions and comments

**Comment by maheshbhuvanagiri** [comment]
Get Middle character- good

Transport on vacation-
1. In the if condition your assigning the same value to it, could you refactor that.

a) Number(d)-- No need to call Number function in this example, as we will be passing number in this example.

Here i added few test cases by passing strings so added conversion function . Now removed both test cases and the conversion

when you pass a string to Number('hi') it would be NaN, I didn't find any if condition checking this case. So, I asked you to remove in this example.

**Comment by amshekar** [comment]
@maheshbhuvanagiri 
Implemented the review comments
Thank you

**Comment by maheshbhuvanagiri** [comment]
@amshekar 
All the tasks looks good.
