### ISSUE TITLE
Home-work-2 #1

### ISSUE THREAD

**Issue by amshekar** [amshekar/epam-js-angular-training#2]
@maheshbhuvanagiri  Please review and provide the comments for homework 2

**Comment by maheshbhuvanagiri** [comment]
@amshekar Please refactor as per below comments

**CalculationWithFunctions**

1. This part of code is repetitive in all the functions from zero to nine
  zero(operator) {
  return operator ? operator(0) : 0;
  }

   Make this logic into a separate function that take the changing parameters 0-9 as input and make use of    
   closure and return the function within that.

**Comment by amshekar** [comment]
@maheshbhuvanagiri  Implemented the comments 

Also please review Homework 4 
fyi
https://github.com/amshekar/epam-js-angular-training/projects/1

**Comment by maheshbhuvanagiri** [comment]
@amshekar 
Everything looks good, but in **calculating-with-functions.js** use single var declaration pattern.

**Comment by amshekar** [comment]
@maheshbhuvanagiri  implemented single var declaration pattern review comment

**Comment by amshekar** [comment]
Implemented the review comments
