### ISSUE TITLE
Please review Home-work #3

### ISSUE THREAD

**Issue by amshekar** [amshekar/epam-js-angular-training#4]
@maheshbhuvanagiri 
Provide your comments

**Comment by maheshbhuvanagiri** [comment]
@amshekar 
**new-with-apply**
1.  Avoid using `new` in the function and achieve the things that `new` does when called as constructor 
    function and return a brand new object from the constructor function

**using-closures-to-share-class-state**
1. I Couldn't see exception thrown if name or weight is not passed.
2. This count property always returns 2, even if we create few more instances of Cat and average would 
    go wrong.

please do changes till here.

**Comment by amshekar** [comment]
@maheshbhuvanagiri 
. Please review and close the review task

**Comment by maheshbhuvanagiri** [comment]
@amshekar  using-closures-to-share-class-state

The weight should be a property created using Object.defineProperty, and cat instances should be able to set this property. total weight should reflect all the weights of the cat instances. better to create Cat as an IIFE.

**Comment by maheshbhuvanagiri** [comment]
changes looks good
